### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by SeyyedKhandon** [hassanzadeh-mj/futuguard-miniproject#1]
Can You please add an online demo for this project?
you can use netlify for this.

**Comment by hassanzadeh-mj** [comment]
yes https://futuguard-miniproject.netlify.app/

**Comment by SeyyedKhandon** [comment]
Thanks, I think it will be great if you could add this link in the main projects `readme.md` and  here in the settings👌
![image](https://user-images.githubusercontent.com/59599950/181694988-b45df306-6c43-497a-b606-4848485e591b.png)
